title: Ted's Time Capsule
description: > # this means to ignore newlines until "baseurl:"
  The blogs and thoughts of Tedley Meralus.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: techgameteddy #if your site has a twitter account, enter it here

# Author Settings
author: Tedley Meralus # add your name
author-img: tedley-bw-cartoon-white-square.png # add your photo
about-author: Senior Software Engineer, Writer, Twin. Always learning and documenting my journey as  I go. # add description
social-twitter: techgameteddy # add your Twitter handle
#social-facebook: tmeralus # add your Facebook handle
social-github: tmeralus # add your Github handle
social-linkedin: tmeralus # add your Linkedin handle
social-studio: 1019studios # add your Email address
social-email: # add your Email address

# Disqus
discus-identifier: techgameteddy # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
