# Site settings
title: Tedley Meralus
email: youremailaddress@gmail.com
description: Linux Engineer and Software Developer
baseurl: "/" # the subpath of your site, e.g. /blog
url: "meralus.com" # the base hostname & protocol for your site

# Social settings
facebook_url:
github_url: https://github.com/tmeralus
gitlab_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/tmeralus
twitter_url: https://twitter.com/techgameteddy

# Build settings
markdown: kramdown
